### ISSUE TITLE
Consider migrating away from `jekyll-assets`

### ISSUE THREAD

**Issue by davemcorwin** [cloud-gov/pages-uswds-jekyll#186]
#### Background (Optional)

@davemcorwin :
I really wanted this template to only depend on Ruby, but I just don't think it's possible, node just seems necessary, and we are still using it for `netlify-cms` and `uswds`.

Meanwhile activity on `jekyll-assets` seems to have stopped and support for Jekyll 4 is not complete. I think we should migrate away from `jekyll-assets` to a possibly more explicit way of handling SASS, JS and other assets.

#### Acceptance Criteria

- [x] jekyll assets is removed from the repo
- [ ] replace with (sprockets, webpacker, rollup, parcel, esbuild, ...) ?
- [x] Change made live via deploy

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by idmken** [comment]
+1 no update since 2018

https://rubygems.org/gems/jekyll-assets/versions/3.0.12

**Comment by idmken** [comment]
This is related to #223

**Comment by drewbo** [comment]
Closed via #314
